# Generated by Django 4.2.3 on 2023-12-28 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0003_rename_user_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Country", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("postal_code", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="billing_details",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_module.billingdetails",
            ),
        ),
    ]
