# Generated by Django 4.2.3 on 2023-12-29 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0007_rename_billing_details_billingdetails_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingdetails",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
