# Generated by Django 4.2.3 on 2023-12-31 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0012_remove_productattribute_product_product_attribute"),
        ("user_module", "0009_favoriteproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favoriteproduct",
            name="product",
        ),
        migrations.AddField(
            model_name="favoriteproduct",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_module.product",
            ),
            preserve_default=False,
        ),
    ]
