# Generated by Django 4.2.3 on 2023-07-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0002_rename_blog_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
