# Generated by Django 4.2.3 on 2023-12-18 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0007_productbrand_product_quantity_sold_product_brand"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={},
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="is_delete",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="url_title",
        ),
    ]
