# Generated by Django 4.2.3 on 2023-12-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0008_alter_productcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="productgallery",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="gallery",
            field=models.ManyToManyField(to="product_module.productgallery"),
        ),
    ]
