# Generated by Django 4.2.3 on 2023-12-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0009_alter_productcategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="productFeatures",
        ),
    ]
