# Generated by Django 4.2.3 on 2023-12-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0011_value_productattribute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattribute",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="attribute",
            field=models.ManyToManyField(to="product_module.productattribute"),
        ),
    ]
