# Generated by Django 4.2.3 on 2023-12-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactus_module", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
