# Generated by Django 4.2.3 on 2023-12-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="created_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
