# Generated by Django 4.2.3 on 2023-12-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blogs_module", "0004_alter_blogs_image"),
        ("comment_module", "0002_alter_comments_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="blog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogs_module.blogs",
            ),
        ),
    ]
