# Generated by Django 4.2.3 on 2023-12-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product_module", "0012_remove_productattribute_product_product_attribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeaderBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/products")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_module.product",
                    ),
                ),
            ],
        ),
    ]
