# Generated by Django 4.2.3 on 2023-12-30 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0012_remove_productattribute_product_product_attribute"),
        ("home_module", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HeaderBanner",
            new_name="HeaderProductBanner",
        ),
    ]
