# Generated by Django 4.2.3 on 2023-12-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0012_remove_productattribute_product_product_attribute"),
        ("home_module", "0002_rename_headerbanner_headerproductbanner"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeaderCategoryBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/products")),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_module.productcategory",
                    ),
                ),
            ],
        ),
    ]
