# Generated by Django 4.2.3 on 2023-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aboutus_module", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("url", models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name="aboutus",
            name="social_media",
            field=models.ManyToManyField(
                blank=True, null=True, to="aboutus_module.socialmedia"
            ),
        ),
    ]
